---
abstract: 'simple, flexible, fun "Testing framework"'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  Test::Base::Less: '0'
  Test::More: '0.98'
  Test::Requires: '0'
  Text::Diff: '0'
configure_requires:
  Module::Build: '0.38'
dynamic_config: 0
generated_by: 'Minilla/v2.1.1, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Test-Kantan
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Test::Kantan:
    file: lib/Test/Kantan.pm
    version: '0.37'
  Test::Kantan::Builder:
    file: lib/Test/Kantan/Builder.pm
  Test::Kantan::Caller:
    file: lib/Test/Kantan/Caller.pm
  Test::Kantan::Expect:
    file: lib/Test/Kantan/Expect.pm
  Test::Kantan::Reporter::Base:
    file: lib/Test/Kantan/Reporter/Base.pm
  Test::Kantan::Reporter::Spec:
    file: lib/Test/Kantan/Reporter/Spec.pm
  Test::Kantan::Reporter::Spec::Message::Base:
    file: lib/Test/Kantan/Reporter/Spec.pm
  Test::Kantan::Reporter::Spec::Message::Diag:
    file: lib/Test/Kantan/Reporter/Spec.pm
  Test::Kantan::Reporter::Spec::Message::Exception:
    file: lib/Test/Kantan/Reporter/Spec.pm
  Test::Kantan::Reporter::Spec::Message::Fail:
    file: lib/Test/Kantan/Reporter/Spec.pm
  Test::Kantan::Reporter::Spec::Message::Pass:
    file: lib/Test/Kantan/Reporter/Spec.pm
  Test::Kantan::Reporter::Spec::MessageGroup:
    file: lib/Test/Kantan/Reporter/Spec.pm
  Test::Kantan::Reporter::TAP:
    file: lib/Test/Kantan/Reporter/TAP.pm
  Test::Kantan::State:
    file: lib/Test/Kantan/State.pm
  Test::Kantan::Suite:
    file: lib/Test/Kantan/Suite.pm
  Test::Kantan::Util:
    file: lib/Test/Kantan/Util.pm
recommends:
  Devel::CodeObserver: '0.11'
requires:
  Module::Load: '0'
  Module::Spy: '0.03'
  Moo: '0'
  Scope::Guard: '0'
  Term::Encoding: '0'
  Test::Deep: '0'
  Try::Tiny: '0'
  perl: '5.010001'
resources:
  bugtracker: https://github.com/tokuhirom/Test-Kantan/issues
  homepage: https://github.com/tokuhirom/Test-Kantan
  repository: git://github.com/tokuhirom/Test-Kantan.git
version: '0.37'
